require('settings')
require('packer-config')
require('colorschemes-config.gruvbox-config')
require('mappings')
require('lualine-config')
require('treesitter-config')
require('autopair-config')
require('trouble-config')
require('telescope-config')
require('lsp-zero-config')

--require('mason-config')
--require('lsp-config.language-servers')
--require('lsp-config.nvim-cmp')
--require('colorschemes-config.nightfox')
--require('nvim-tree-config')
--require('barbar-config')
